// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3K2ZjnmFaHnt467f2MMHvCX6jbv8XTAI',
    appId: '1:806813122117:web:9ae96528e7990e0c69ed2c',
    messagingSenderId: '806813122117',
    projectId: 'mindmatchgame-bc11b',
    authDomain: 'mindmatchgame-bc11b.firebaseapp.com',
    storageBucket: 'mindmatchgame-bc11b.firebasestorage.app',
    measurementId: 'G-NRFJSWQ4KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-oUOB_8PIz2EeTiIx0Y6H6izSo-ZsVo',
    appId: '1:806813122117:android:d8866be6784c284469ed2c',
    messagingSenderId: '806813122117',
    projectId: 'mindmatchgame-bc11b',
    storageBucket: 'mindmatchgame-bc11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp51qjyc7UJ2VKBcmu-EkxOtKQCqBt3iU',
    appId: '1:806813122117:ios:08bf6b46b13cf72069ed2c',
    messagingSenderId: '806813122117',
    projectId: 'mindmatchgame-bc11b',
    storageBucket: 'mindmatchgame-bc11b.firebasestorage.app',
    iosBundleId: 'com.example.mindMatchGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp51qjyc7UJ2VKBcmu-EkxOtKQCqBt3iU',
    appId: '1:806813122117:ios:08bf6b46b13cf72069ed2c',
    messagingSenderId: '806813122117',
    projectId: 'mindmatchgame-bc11b',
    storageBucket: 'mindmatchgame-bc11b.firebasestorage.app',
    iosBundleId: 'com.example.mindMatchGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3K2ZjnmFaHnt467f2MMHvCX6jbv8XTAI',
    appId: '1:806813122117:web:91e7534b9040a78769ed2c',
    messagingSenderId: '806813122117',
    projectId: 'mindmatchgame-bc11b',
    authDomain: 'mindmatchgame-bc11b.firebaseapp.com',
    storageBucket: 'mindmatchgame-bc11b.firebasestorage.app',
    measurementId: 'G-C9RD0E9KZE',
  );
}
